services:
    _defaults:
        public: true
        autowire: true

    Migrify\NeonToYaml\:
        resource: '../src'
        exclude:
            - '../src/HttpKernel/NeonToYamlKernel.php'

    Symplify\SmartFileSystem\SmartFileSystem: null

    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: null
    Symfony\Component\Console\Style\SymfonyStyle:
        factory: ['@Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory', 'create']

    Symplify\SmartFileSystem\Finder\FinderSanitizer: null
    Symplify\PackageBuilder\Strings\StringFormatConverter: null
